openapi: 3.0.0
x-stoplight:
  id: w9c5iq3rh9v42
info:
  title: Agent 节点开放的接口
  version: '1.0'
  description: Agent 节点开放的接口
  license:
    name: NONE
    url: NONE
  termsOfService: 'https://github.com/vela-ssoc'
  contact:
    name: ssoc
    url: 'https://github.com/vela-ssoc'
    email: hnwzy@live.com
servers:
  - url: /api/v1
    description: /api/v1
tags:
  - name: 程序事件
    description: agent 程序事件通知接口
  - name: 通用请求响应
    description: 通用请求响应类型的接口
  - name: 通用 websocket 接口
    description: 通用 websocket 接口
paths:
  /afn/app/update:
    parameters: []
    post:
      summary: 通知程序需要升级
      operationId: post-afn-app-update
      responses:
        '200':
          description: OK
      description: 当收到程序升级指令时，代表 `Agent` 需要向 `Broker` 发起请求检查更新。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                semver:
                  type: string
                  x-stoplight:
                    id: xm8rd711zfytn
                  description: 要求升级的版本号，如果为空则代表需要升级到最新版
            examples:
              请求示例:
                value:
                  server: 1.2.3
        description: ''
      tags:
        - 程序事件
  '/arr/{path}':
    parameters:
      - schema:
          type: string
        name: path
        in: path
        required: true
        description: 路径
    get:
      summary: 通用请求响应类接口
      operationId: get-arr-path
      responses:
        '200':
          description: OK
      description: 通用请求响应类接口
      tags:
        - 通用请求响应
    post:
      summary: 请求响应类型的通用接口
      operationId: post-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
    put:
      summary: 通用请求响应类接口
      operationId: put-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
    patch:
      summary: 通用请求响应类接口
      operationId: patch-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
    delete:
      summary: 通用请求响应类接口
      operationId: delete-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
    head:
      summary: 通用请求响应类接口
      operationId: head-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
    options:
      summary: 通用请求响应类接口
      operationId: options-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
    trace:
      summary: 通用请求响应类接口
      operationId: trace-arr-path
      responses:
        '200':
          description: OK
      tags:
        - 通用请求响应
      description: 通用请求响应类接口
  '/aws/{path}':
    parameters:
      - schema:
          type: string
        name: path
        in: path
        required: true
        description: 自定义路径
    get:
      summary: websocket 接口
      tags:
        - 通用 websocket 接口
      responses:
        '100':
          description: websocket 建立成功
        '200':
          description: 不允许返回 `2xx` 级错误
        '400':
          description: 返回具体的错误信息
      operationId: get-aws-path
      description: '`/api/v1/aws/*path` '
components:
  schemas: {}
