openapi: 3.1.0
x-stoplight:
  id: c9vjkvk4f45fu
info:
  title: Agent 与 Broker 节点对接文档
  version: '1.0'
  description: Agent 与 Broker 节点对接文档
  contact:
    name: ssoc
    url: 'https://github.com/vela-ssoc'
  termsOfService: 'https://github.com/vela-ssoc'
  summary: Agent 与 Broker 节点对接文档
  x-logo:
    url: logo.ico
tags:
  - name: Agent
    description: Agent 需要提供的接口
  - name: Broker
    description: Broker 需要提供的接口
servers:
  - url: /api/v1
    description: 基础路径
paths:
  /edict/task/status:
    post:
      summary: 抓取 agent 上任务运行状态
      operationId: post-edict-task-status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskReport'
      tags:
        - Agent
      description: 抓取 agent 上任务运行状态
  /edict/task/diff:
    post:
      summary: 配置有差异时回调接口
      operationId: post-edict-task-diff
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskReport'
      tags:
        - Agent
      description: 配置有差异时回调接口
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDiff'
  /substance/task:
    post:
      summary: 上报配置运行状态返回差异信息
      operationId: post-substance-task
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDiff'
      tags:
        - Broker
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskReport'
        description: ''
components:
  schemas:
    TaskDiff:
      title: TaskDiff
      x-stoplight:
        id: ztigrtssizk6y
      type: object
      description: '中心端比对后返回的差异信息，请c[Go struct 定义]'
      properties:
        removes:
          type: array
          items:
            type: integer
        updates:
          type: array
          items:
            $ref: '#/components/schemas/TaskChunk'
      examples:
        - removes:
            - 1234567890
          updates:
            - id: 11223344556677
              name: kafka
              dialect: true
              hash: 28f35476af08ba7d170529ec46484b98
              chunk: cHJpbnQoIkhlbGxvIik=
    TaskChunk:
      title: TaskChunk
      x-stoplight:
        id: ma43hfagscnvy
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        dialect:
          type: boolean
        hash:
          type: string
        chunk:
          type: string
      examples:
        - id: 11223344556677
          name: kafka
          dialect: true
          hash: 28f35476af08ba7d170529ec46484b98
          chunk: cHJpbnQoIkhlbGxvIik=
    TaskRunner:
      title: TaskRunner
      x-stoplight:
        id: w11u8tn7n60xh
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        status:
          type: string
      examples:
        - name: kafka.sub
          type: kafka
          status: running
    TaskStatus:
      title: TaskStatus
      x-stoplight:
        id: mv0o6vtb7qsqy
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        dialect:
          type: boolean
        hash:
          type: string
        uptime:
          type: string
        from:
          type: string
        runners:
          type: array
          items:
            $ref: '#/components/schemas/TaskRunner'
      examples:
        - id: 1133847578322
          name: kafka
          dialect: true
          hash: 28f35476af08ba7d170529ec46484b98
          uptime: '2023-05-23T02:42:26.968Z'
          from: tunnel
          runners:
            - name: kafka.sub
              type: kafka
              status: running
    TaskReport:
      title: TaskReport
      x-stoplight:
        id: dvqomtdddc6j7
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskStatus'
      examples:
        - tasks:
            - id: 1133847578322
              name: kafka
              dialect: true
              hash: 28f35476af08ba7d170529ec46484b98
              uptime: '2023-05-23T02:42:26.968Z'
              from: tunnel
              runners:
                - name: kafka.sub
                  type: kafka
                  status: running
