openapi: 3.1.0
x-stoplight:
  id: tq50t1f1jmmi2
info:
  title: Broker 节点为 Agent 开放的接口
  version: '1.0'
  description: Broker 节点为 Agent 开放的接口，用于 `broker` 和 `agent` 之间的业务交互。
  summary: broker 开放文档
  x-logo:
    url: logo.ico
  contact:
    name: ssoc team
    url: 'https://github.com/vela-ssoc'
    email: hnwzy@live.com
  termsOfService: 'https://github.com/vela-ssoc'
servers:
  - url: 'http://spdy-tunnel/api/v1'
    description: /api/v1
tags:
  - name: 配置运行
    description: 配置下发上报相关接口
  - name: 三方文件
    description: 中心端三方文件
paths:
  /task:
    post:
      summary: 上报运行的配置状态
      operationId: post-task
      responses:
        '200':
          description: 响应报文待定
      tags:
        - 配置运行
      description: 上报运行的配置状态
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: 请求报文待定
  /third:
    get:
      summary: 下载三方文件
      tags:
        - 三方文件
      responses:
        '200':
          description: 文件下载流
          content:
            application/octet-stream:
              schema:
                type: object
                properties: {}
          headers:
            Content-Disposition:
              schema:
                type: string
              description: 文件描述信息
        '304':
          description: 说明文件 `hash` 一致，文件没有变化，无需重复下载。
        '404':
          description: 文件不存在
      operationId: get-third
      description: |-
        `id`: 如果文件 ID 有效（id > 0），则以 ID 查询下载三方文件。
        `name`: 当文件 ID 未填写时则以文件名查询下载三方文件。
        `hash`: 服务端则会比较 `hash` 是否一致，一致则返回 `304` 状态码，不一致则返回最新的文件下载流。

        > `id` 和 `name` 只需其中一个有值就可以了，如果都有值则以 `id` 为准。
      parameters:
        - schema:
            type: number
          in: query
          name: id
          description: 文件 ID
        - schema:
            type: string
            example: hosts.txt
          in: query
          name: name
          description: 文件名
        - schema:
            type: string
          in: query
          name: hash
          description: 文件校验码（默认使用 `SHA-1` 算法）
components:
  schemas: {}
